apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-psrlraty
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-psrlraty:536916642790918a83b590128043ac696fa4436b@sha256:7c2987e04afb747c8fb94c153fd68a15ccb6cd52d085abecd5076e80445f8cd4
          name: container-image
